<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hal" nsURI="http://ca.mcgill/emf/examples/hal" nsPrefix="hal">
  <eClassifiers xsi:type="ecore:EClass" name="Home">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" lowerBound="1" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityLogs" upperBound="-1"
        eType="#//Log" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actuatorType" eType="#//ActuatorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isWindowOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHeaterOn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" upperBound="-1"
        eType="#//Device" eOpposite="#//Device/room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" eType="#//Room" eOpposite="#//Room/device"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorType" eType="#//SensorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HalSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rules" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="home" eType="#//Home" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" upperBound="-1"
        eType="#//Device" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" lowerBound="1"
        upperBound="-1" eType="#//PreCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
    <eLiterals name="TemperatureSensor"/>
    <eLiterals name="MovementSensor" value="1"/>
    <eLiterals name="LightSensor" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActuatorType">
    <eLiterals name="Heater"/>
    <eLiterals name="Lock" value="1"/>
    <eLiterals name="LightSwitch" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Log">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" upperBound="-1"
        eType="#//Sensor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicpiece" upperBound="-1"
        eType="#//LogicPiece" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuator" upperBound="-1"
        eType="#//Actuator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicGate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//LogicType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicType">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="NOT" value="2"/>
    <eLiterals name="ORNOT" value="3"/>
    <eLiterals name="ANDNOT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicPiece">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicpiece" upperBound="-1"
        eType="#//LogicPiece"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singlecondition" upperBound="-1"
        eType="#//SingleCondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicgate" upperBound="-1"
        eType="#//LogicGate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
