/**
 *
 * $Id$
 */
package ca.mcgill.emf.examples.hal.validation;

import ca.mcgill.emf.examples.hal.ActuatorTpye;
import ca.mcgill.emf.examples.hal.ActuatorType;


/**
 * A sample validator interface for {@link ca.mcgill.emf.examples.hal.Actuator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActuatorValidator {
	boolean validate();

	boolean validateActuatorType(ActuatorType value);

	boolean validateActuatorType(ActuatorTpye value);

}
