/**
 *
 * $Id$
 */
package ca.mcgill.emf.examples.hal.validation;

import ca.mcgill.emf.examples.hal.Home;
import ca.mcgill.emf.examples.hal.Rules;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.mcgill.emf.examples.hal.HalSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HalSystemValidator {
	boolean validate();

	boolean validateRules(EList<Rules> value);
	boolean validateHome(Home value);

	boolean validateHome(EList<Home> value);
}
