/**
 *
 * $Id$
 */
package ca.mcgill.emf.examples.hal.validation;

import ca.mcgill.emf.examples.hal.Device;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.mcgill.emf.examples.hal.Room}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoomValidator {
	boolean validate();

	boolean validateDevice(EList<Device> value);
	boolean validateName(String value);
	boolean validateIsWindowOpen(boolean value);
	boolean validateIsHeaterOn(boolean value);
}
