/**
 *
 * $Id$
 */
package ca.mcgill.emf.examples.hal.validation;

import ca.mcgill.emf.examples.hal.SensorType;


/**
 * A sample validator interface for {@link ca.mcgill.emf.examples.hal.Sensor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SensorValidator {
	boolean validate();

	boolean validateSensorType(SensorType value);

}
